### ISSUE TITLE
this is the issue which it's showing while running the docker file

### ISSUE THREAD

**Issue by alphapibeta** [anibali/docker-pytorch#25] opened 2020-04-26 11:55 UTC
The command '/bin/sh -c /home/user/miniconda/bin/conda create -y --name py36 python=3.6.9  && /home/user/miniconda/bin/conda clean -ya' returned a non-zero code: 127

**Comment by anibali** [comment] 2020-04-26 13:10
Thanks for the report, I believe that the issue is that the download request for miniconda now responds with a redirect, so I need to update the `curl` command to follow redirects. If you want to try to fix that yourself right now, edit the following line of whatever Dockerfile you're using to be `curl -sLo` instead of `curl -so`:

https://github.com/anibali/docker-pytorch/blob/3df310aa3716233e90a1a9ba3ecbca3bf1269f3e/Dockerfile.template#L28

I'll probably push a fix to this repo sometime tomorrow.

**Comment by anibali** [comment] 2020-04-27 02:17
Fixed in https://github.com/anibali/docker-pytorch/commit/537d8961d59ccb6056d3dd3b3e755ec75c86d045.

**Closed as completed by anibali** 2020-04-27 02:17 UTC
Labels: bug
